# Generated by Django 3.0.8 on 2021-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('coverURL', models.CharField(default='', max_length=1024)),
                ('correctAnswer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('singer', models.CharField(default='', max_length=100)),
                ('album', models.CharField(default='', max_length=100)),
                ('coverFile', models.BinaryField()),
                ('coverURL', models.CharField(default='', max_length=1024)),
                ('songFile', models.BinaryField()),
                ('songURL', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver', models.IntegerField(default=0)),
            ],
        ),
    ]
